# Generated by Django 4.2.2 on 2023-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_suppliercard_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercard',
            name='contacts',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
